### ISSUE TITLE
external link in menu

### ISSUE THREAD

**Issue by cristiursachi** [halibegic/merlin#2]
It seems you cannot put an external link to a top menu item:

                [a href="http://www.google.com" ] google [/a]
             

Does not open it, any idea how can I force open it?

**Comment by halibegic** [comment]
Hi,

To put an external link just use the class `"external"`
```
<a class="external" href="https://www.google.com">Google</a>
```

**Comment by cristiursachi** [comment]
Great, many thanks!!
