### ISSUE TITLE
Any way to visualize portfolio items and to show more information about it?

### ISSUE THREAD

**Issue by alvarosaco** [halibegic/merlin#3]
Hello Hasan @halibegic,

Congratulations for the template! 
I'm looking for the way to show more information about an item portfolio when user click it. Any tips?

Thanks so much,

Álvaro

**Comment by halibegic** [comment]
Hi Álvaro,
Portfolio now allows users to see details for particular item. I hope you'll like it.

**Comment by alvarosaco** [comment]
Wow! Magic! That's really cool! :) Just like I was thinking. I didn't know Venobox.

Thanks so much again Hasan

**Comment by alvarosaco** [comment]
Hi @halibegic 
Do you know any way to show the portfolio items with different URLs?

**Comment by halibegic** [comment]
Any example?

**Comment by alvarosaco** [comment]
I mean a way to give someone the URL for certain portfolio item like "https://halibegic.info/p/merlin/work.html" and keep integrated with the styles and the main site.
